# This is a sample build configuration for Javascript (Node.js).
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: rhinogram/node-awscli
options:
  docker: true

pipelines:
  branches:
    master:
      - step:
          name: Deploy to production
          deployment: production
          caches:
            - node
          script:
            - npm install
            - npm run-script build && aws s3 cp ./build s3://rapid-playground/ --recursive
